# Generated by Django 4.1.7 on 2023-02-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_task_station_alter_station_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='task',
            new_name='station',
        ),
    ]
